name: pipeline
description: Manage Jenkins pipelines
methods:
  stages:
    description: List stages for a Pipeline build
    http:
      method: GET
      path: "job/{{ job_name | replace('/', '/job/') }}/{{ build_number }}/wfapi/describe"
    params:
      path:
        - name: job_name
          type: string
          argument: true
        - name: build_number
          type: int
          argument: true
    output:
      items_path: $.stages
      fields:
        - name: name
          alias: Stage
        - name: status
          alias: Status
        - name: durationMillis
          alias: Duration
  log:
    description: Get log output for a Pipeline step
    http:
      method: GET
      path: "job/{{ job_name | replace('/', '/job/') }}/{{ build_number }}/execution/node/{{ node_id }}/wfapi/log"
    params:
      path:
        - name: job_name
          type: string
          argument: true
        - name: build_number
          type: int
          argument: true
        - name: node_id
          type: string
          argument: true
  validate:
    description: Validate a Jenkinsfile against the server
    type: plugin:jenkins_pipeline_validate
    params:
      body:
        - name: jenkinsfile
          type: file
          argument: true
  pending:
    description: Show pending input actions for a Pipeline build
    http:
      method: GET
      path: "job/{{ job_name | replace('/', '/job/') }}/{{ build_number }}/wfapi/pendingInputActions"
    params:
      path:
        - name: job_name
          type: string
          argument: true
        - name: build_number
          type: int
          argument: true