name: plugin
description: Manage Jenkins plugins
methods:
  list:
    description: List installed Jenkins plugins
    http:
      method: GET
      path: pluginManager/api/json
      query:
        tree: "plugins[shortName,version,active,hasUpdate]"
    output:
      items_path: $.plugins
      fields:
        - name: shortName
          alias: Name
        - name: version
          alias: Version
        - name: active
          alias: Active
        - name: hasUpdate
          alias: Update
  get:
    description: Show details for a single plugin
    type: plugin:jenkins_plugin_get
    params:
      body:
        - name: short_name
          type: string
          argument: true
  install:
    description: Install one or more plugins (NAME or NAME@VERSION)
    type: plugin:jenkins_plugin_install
    params:
      body:
        - name: plugins
          type: string
          multiple: true
          argument: true
  uninstall:
    description: Uninstall a plugin
    http:
      method: POST
      path: "pluginManager/plugin/{{ short_name }}/doUninstall"
    params:
      path:
        - name: short_name
          type: string
          argument: true
  check-updates:
    description: Check for plugin updates
    http:
      method: POST
      path: pluginManager/checkUpdates
    output:
      format: json
  restart:
    description: Restart a plugin
    http:
      method: POST
      path: "pluginManager/plugin/{{ short_name }}/restart"
    params:
      path:
        - name: short_name
          type: string
          argument: true